import {
  AgentLog,
  AgentMemory,
  AgentPermission,
  AgentRun,
  AgentTask,
  AgentTool,
  AgentApproval,
  AgentPromptVersion,
  AgentEvent,
  WorkspaceKnowledge,
  AgentEval,
  WorkflowCondition,
  WorkflowFailure,
  WorkflowTrigger,
} from "./types";

export type AiCollectionKey =
  | "agent_runs"
  | "agent_logs"
  | "agent_permissions"
  | "agent_memory"
  | "agent_tasks"
  | "agent_tools"
  | "agent_approvals"
  | "agent_prompt_versions"
  | "agent_events"
  | "workspace_knowledge"
  | "agent_evals"
  | "workflow_triggers"
  | "workflow_conditions"
  | "workflow_failures";

type CollectionSchema<T> = {
  required: (keyof T)[];
  optional?: (keyof T)[];
};

export const AI_COLLECTION_SCHEMAS: Record<AiCollectionKey, CollectionSchema<any>> = {
  agent_runs: {
    required: ["workspaceId", "agentId", "status", "triggerType", "tokensIn", "tokensOut", "createdAt", "updatedAt"] as (keyof AgentRun)[],
    optional: [
      "taskId",
      "triggerContext",
      "startedAt",
      "finishedAt",
      "durationMs",
      "input",
      "output",
      "error",
      "usdCost",
      "model",
      "correlationId",
      "createdBy",
      "updatedBy",
      "status",
      "userId",
      "leadId",
      "jobId",
      "estimateId",
      "contactId",
      "conversationId",
    ] as (keyof AgentRun)[],
  },
  agent_logs: {
    required: ["workspaceId", "runId", "agentId", "level", "message", "createdAt", "updatedAt"] as (keyof AgentLog)[],
    optional: [
      "payload",
      "stepId",
      "spanId",
      "createdBy",
      "updatedBy",
      "status",
      "userId",
      "leadId",
      "jobId",
      "estimateId",
      "contactId",
      "conversationId",
    ] as (keyof AgentLog)[],
  },
  agent_permissions: {
    required: ["workspaceId", "agentId", "toolKey", "scope", "allowed", "createdAt", "updatedAt"] as (keyof AgentPermission)[],
    optional: [
      "scopeId",
      "expiresAt",
      "grantedByUserId",
      "revokedAt",
      "conditions",
      "notes",
      "createdBy",
      "updatedBy",
      "status",
      "userId",
      "leadId",
      "jobId",
      "estimateId",
      "contactId",
      "conversationId",
    ] as (keyof AgentPermission)[],
  },
  agent_memory: {
    required: ["workspaceId", "agentId", "scope", "key", "value", "source", "createdAt", "updatedAt"] as (keyof AgentMemory)[],
    optional: [
      "scopeId",
      "summary",
      "confidence",
      "lastSeenAt",
      "expiresAt",
      "tags",
      "createdBy",
      "updatedBy",
      "status",
      "userId",
      "leadId",
      "jobId",
      "estimateId",
      "contactId",
      "conversationId",
    ] as (keyof AgentMemory)[],
  },
  agent_tasks: {
    required: [
      "workspaceId",
      "createdByUserId",
      "source",
      "status",
      "priority",
      "agentId",
      "agentType",
      "context",
      "input",
      "tokensIn",
      "tokensOut",
      "usdEstimate",
      "attempts",
      "maxAttempts",
      "createdAt",
      "updatedAt",
    ] as (keyof AgentTask)[],
    optional: [
      "jobId",
      "leadId",
      "estimateId",
      "contactId",
      "roomId",
      "output",
      "error",
      "code",
      "message",
      "stack",
      "cost",
      "lockedBy",
      "lockedAt",
      "startedAt",
      "finishedAt",
      "createdBy",
      "updatedBy",
      "status",
      "userId",
      "conversationId",
    ] as (keyof AgentTask)[],
  },
  agent_tools: {
    required: [
      "workspaceId",
      "key",
      "name",
      "description",
      "risk",
      "requiresApproval",
      "defaultEnabled",
      "status",
      "createdAt",
      "updatedAt",
    ] as (keyof AgentTool)[],
    optional: [
      "createdBy",
      "updatedBy",
      "status",
      "userId",
      "leadId",
      "jobId",
      "estimateId",
      "contactId",
      "conversationId",
    ] as (keyof AgentTool)[],
  },
  agent_approvals: {
    required: [
      "workspaceId",
      "taskId",
      "agentId",
      "toolKey",
      "proposal",
      "summary",
      "payload",
      "status",
      "requestedBy",
      "type",
      "createdAt",
      "updatedAt",
    ] as (keyof AgentApproval)[],
    optional: [
      "preview",
      "reviewedByUserId",
      "reviewedAt",
      "expiresAt",
      "createdBy",
      "updatedBy",
      "status",
      "userId",
      "leadId",
      "jobId",
      "estimateId",
      "contactId",
      "conversationId",
    ] as (keyof AgentApproval)[],
  },
  agent_prompt_versions: {
    required: [
      "workspaceId",
      "agentId",
      "version",
      "systemPrompt",
      "policyPrompt",
      "stylePrompt",
      "toolsPrompt",
      "createdByUserId",
      "createdAt",
      "updatedAt",
    ] as (keyof AgentPromptVersion)[],
    optional: [
      "label",
      "createdBy",
      "updatedBy",
      "status",
      "userId",
      "leadId",
      "jobId",
      "estimateId",
      "contactId",
      "conversationId",
    ] as (keyof AgentPromptVersion)[],
  },
  agent_events: {
    required: ["workspaceId", "agentId", "type", "payload", "createdAt", "updatedAt"] as (keyof AgentEvent)[],
    optional: [
      "relatedEntityType",
      "relatedEntityId",
      "userId",
      "status",
      "error",
      "createdBy",
      "updatedBy",
      "leadId",
      "jobId",
      "estimateId",
      "contactId",
      "conversationId",
    ] as (keyof AgentEvent)[],
  },
  workspace_knowledge: {
    required: ["workspaceId", "title", "visibility", "createdAt", "updatedAt"] as (keyof WorkspaceKnowledge)[],
    optional: [
      "type",
      "body",
      "content",
      "tags",
      "status",
      "sourceUrl",
      "createdBy",
      "updatedBy",
      "userId",
      "leadId",
      "jobId",
      "estimateId",
      "contactId",
      "conversationId",
    ] as (keyof WorkspaceKnowledge)[],
  },
  agent_evals: {
    required: ["workspaceId", "agentId", "name", "status", "type", "createdAt", "updatedAt"] as (keyof AgentEval)[],
    optional: [
      "testCases",
      "input",
      "expectedTraits",
      "bannedBehaviors",
      "lastRunAt",
      "lastScore",
      "userId",
      "jobId",
      "leadId",
      "score",
      "feedback",
      "metadata",
      "createdBy",
      "updatedBy",
      "status",
      "userId",
      "leadId",
      "jobId",
      "estimateId",
      "contactId",
      "conversationId",
    ] as (keyof AgentEval)[],
  },
  workflow_triggers: {
    required: ["workspaceId", "workflowId", "source", "status", "firedAt", "createdAt", "updatedAt"] as (keyof WorkflowTrigger)[],
    optional: [
      "eventKey",
      "payload",
      "processedAt",
      "error",
      "correlationId",
      "createdBy",
      "updatedBy",
      "status",
      "userId",
      "leadId",
      "jobId",
      "estimateId",
      "contactId",
      "conversationId",
    ] as (keyof WorkflowTrigger)[],
  },
  workflow_conditions: {
    required: ["workspaceId", "workflowId", "conditionKey", "operator", "expectedValue", "createdAt", "updatedAt"] as (keyof WorkflowCondition)[],
    optional: [
      "lastEvaluatedAt",
      "lastResult",
      "context",
      "createdBy",
      "updatedBy",
      "status",
      "userId",
      "leadId",
      "jobId",
      "estimateId",
      "contactId",
      "conversationId",
    ] as (keyof WorkflowCondition)[],
  },
  workflow_failures: {
    required: ["workspaceId", "workflowId", "runId", "message", "status", "occurredAt", "createdAt", "updatedAt"] as (keyof WorkflowFailure)[],
    optional: [
      "stepId",
      "errorCode",
      "details",
      "resolvedAt",
      "resolvedByUserId",
      "retryAttempt",
      "createdBy",
      "updatedBy",
      "status",
      "userId",
      "leadId",
      "jobId",
      "estimateId",
      "contactId",
      "conversationId",
    ] as (keyof WorkflowFailure)[],
  },
};
